# to be used to start up production Swarm stack-
# NOT YET READY for docker stack deploy
version: "3.9"
services:
  nginx:
    image: dubrowski/survey-system-nginx:1.0.0
    networks:
      - survey-net
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
  php:
    image: dubrowski/survey-system-php:1.0.0
    networks:
      - survey-net
    depends_on:
      - mysql
    volumes:
      - ./src/:/var/www/html/
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=survey_system
      - MYSQL_HOST=mysql:3306
    secrets:
      - mysql-user
      - mysql-password
  mysql:
    image: mysql
    networks:
      - survey-net
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-password
      - MYSQL_USER_FILE=/run/secrets/mysql-user
    secrets:
      - mysql-root-password
      - mysql-password
      - mysql-user
# must create this overlay network before deployment
networks:
  survey-net:
# must create secret before deployment
secrets:
  mysql-root-password:
    external: true
  mysql-password:
    external: true
  mysql-user:
    external: true
