# to be used to start up production Swarm stack-
# NOT YET READY for docker stack deploy
version: "3.1"
services:
  nginx:
    image: dubrowski/survey-system-nginx
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    image: dubrowski/survey-system-php
    networks:
      - internal
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    environment:
      - MYSQL_DATABASE=survey_system
      - MYSQL_HOST=mysql:3306
      - MYSQL_USER=root
    secrets:
      - mysql-root-password
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
    secrets:
      - mysql-root-password
networks:
  internal:
    driver: bridge
# must create secret before deployment
secrets:
  mysql-root-password:
    external: true
